### ISSUE TITLE
Pagerduty Datasource not available in Panel query after Successful test and save

### ISSUE THREAD

**Issue by primeroz** [xginn8/grafana-pagerduty#1]
I am sure i am doing something wrong but, i created Pagerduty Datasource ( with access key ) and the Test+Save worked. I can see the datasource available in the list of Datasources

When i try to create a panel though the pagerduty datasource is not available in the list of datasources , and if i select it to be default then all the panels break with error "t.query is not available" 

Is there something special to do to use this datasource ? 
thanks

**Comment by jahnavi310** [comment]
facing the same issue, any updates on the above^^?

thanks in advance!

**Comment by xginn8** [comment]
This issue should be fixed as of the 0.1.0 release. Please let me know if you are still having problems!

**Comment by MarshallKiruba** [comment]
Hi, First of all it's an wonderful work. So helpful.

Am facing the same issue as reported above. 

Thank you : )

**Comment by sudh33ra** [comment]
facing the same issue. Installed it today

**Comment by xginn8** [comment]
@sudh33ra & @MarshallKiruba this datasource is annotation-only, so it cannot be used in normal panel views. Are you able to annotate other panels using this datasource?

**Comment by hungdohuy** [comment]
Hello, i think everybody have the same issue? Is there anyone able to make it work for showing up in the panel creation?
