### ISSUE TITLE
Grafana 7.x support

### ISSUE THREAD

**Issue by vgwshouse** [xginn8/grafana-pagerduty#20]
Do you have any plans to support the new plugin structure in Grafana 7.x?

Thank you!

**Comment by xginn8** [comment]
Hi @vgwshouse, no plans yet but mostly due to lack of time. PRs welcome!!

**Comment by vgwshouse** [comment]
@xginn8 Thank you! I am going to try to squeeze in some time and will PR when it is at least a bit functional.
