### ISSUE TITLE
Panel error "e.toLowerCase is not a function" when hovering over PD annotations (Grafana v8.1.2)

### ISSUE THREAD

**Issue by Neil-Spek** [xginn8/grafana-pagerduty#24]
**Grafana version:** 8.1.2
**PagerDuty plugin version:** 0.2.2
**Browser: Chrome:** 94.0.4606.61 (Official Build)
**Affected chart type:** Time series

**Underlying error:**
angular.js:15697 TypeError: e.toLowerCase is not a function
    at O (tags.ts:70)
    at M (tags.ts:8)
    at Object.link (tags.ts:17)
    at angular.js:1391
    at angular.js:11370
    at Pt (angular.js:11376)
    at at (angular.js:10695)
    at angular.js:9942
    at angular.js:9807
    at angular.js:10221 '<span class="label label-tag small" ng-repeat="tag in tags" tag-color-from-name="tag">'

![image](https://user-images.githubusercontent.com/56037422/134658888-97180a1f-143e-4674-929f-0b369386ce77.png)

Exploring the DOM I have noticed (within datasource.js) the incident object has a tags property which contains a list of items, however the item: d.incident_number is of type integer causing failure upon hover over of the annotation as the toLowerCase function is expecting a string.

**Suggested fix:**
Change to line:98 of datasource.js as follows:

Original line `tags: [d.type, d.incident_key, d.incident_number, d.status, d.service.id],`
to be replaced with `tags: [d.type, d.incident_key, d.incident_number.toString(), d.status, d.service.id],`

**Comment by pavelpikatamcs** [comment]
@xginn8 can this be released please? I installed the plugin just now, and it still has this error

**Comment by TylerLubeck** [comment]
Echoing @pavelpikatamcs - would you mind uploading this to the grafana marketplace as well?

**Comment by dabernasty** [comment]
@xginn8 would love to have this update on the Grafana.com repository of plugins -- can you please upload? Heres some instructions on the required process: https://grafana.com/docs/grafana/latest/developers/plugins/package-a-plugin/#maintain-your-plugin
