### ISSUE TITLE
Pagerduty Data source  not listed during dashboard creation

### ISSUE THREAD

**Issue by MarshallKiruba** [xginn8/grafana-pagerduty#4]
Hi

First of thanks for your wonderful work.

But am facing the below issue.

When am trying to create a panel though the pagerduty datasource. It is not available in the list of datasources , and if I select it to be default then all the panels break with error "t.query is not available"

Thanks in advance : )

**Comment by xginn8** [comment]
This datasource is annotation-only, so you cannot use it to create panels. You can however annotate those panels with event information.
