### ISSUE TITLE
Grafana 6.5.x: Data source is not working (code: undefined)

### ISSUE THREAD

**Issue by anthosz** [xginn8/grafana-pagerduty#8]
Hello,

I just try this data source but doesn't works with Grafana 6 apparently.

Best regards,

**Comment by xginn8** [comment]
Hi @anthosz,

I've just tested this datasource using Grafana 6.5.2 and can confirm it's working, can you describe a bit more about what is not working for you?

**Comment by mudasirmirza** [comment]
Hi,
I am also facing same with Grafana 6.6.0

The http call "api/datasources/proxy/28/pagerduty/incidents" returns "401 Unauthorized" code and in debugger console I see "message: "Unexpected error""

Nothing else is there to show any other information.

Regards,

**Comment by mudasirmirza** [comment]
Ok, 

The thing is we need a USER level REST API Token and not the Events V2 API Key. Create API Token from your User Profile -> User Settings tab and it will work

**Comment by xginn8** [comment]
Thanks for the note @mudasirmirza, I've updated that in the README in 383ea92dcc6cd014df2c90920ee724f547caf74d.
