### ISSUE TITLE
Can't see the PagerDuty plugin as a data source in Grafana 6.5.2

### ISSUE THREAD

**Issue by swedishmike** [xginn8/grafana-pagerduty#9]
I might be doing something stupid here or miss an vital step so apologies up front.

I've successfully installed the plugin as per the instructions with `grafana-cli plugins install xginn8-pagerduty-datasource`.

After that I restarted the Grafana daemon and logged back on to Grafana. 

I've set up the data source under Configuration / Data Sources, complete with my API key, and when I hit `Save & Test` it all seems good and happy.

However, when I try `Add Panel` I can't see the Pager Duty data source in the `QUERY` dropdown where I'd expect to see it. 

I've tried a couple of different visualization types to no avail.

Any ideas as to what I might be doing wrong?

**Comment by xginn8** [comment]
Closing in favor of #8

**Comment by xginn8** [comment]
Hi @swedishmike, this datasource is currently *annotation-only* so you won't be able to add it as a regular query panel.
